# Generated by Django 4.0.6 on 2022-08-08 19:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball')], max_length=250)),
                ('gameID', models.CharField(max_length=50)),
                ('player1', models.CharField(max_length=250)),
                ('player2', models.CharField(max_length=250)),
                ('player1_odd', models.FloatField()),
                ('player2_odd', models.FloatField()),
                ('draw_odds', models.FloatField()),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_game', models.CharField(max_length=250)),
                ('ticket_code', models.CharField(max_length=10)),
                ('ticket_option', models.CharField(choices=[('Won', 'Won'), ('Lost', 'Lost'), ('Void', 'Void')], max_length=10)),
                ('ticket_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predict', models.CharField(choices=[('1x', '1x'), ('x2', 'x2'), ('Draw', 'Draw')], max_length=25)),
                ('slip_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('picked_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbench.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_result', models.CharField(choices=[('1x', '1x'), ('x2', 'x2'), ('Draw', 'Draw')], max_length=25)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workbench.game')),
            ],
        ),
    ]
