# Generated by Django 4.0.6 on 2022-08-08 23:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workbench', '0003_alter_slip_picked_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=10)),
                ('ticket_option', models.CharField(choices=[('Won', 'Won'), ('Lost', 'Lost'), ('Void', 'Void')], max_length=10)),
                ('ticket_date', models.DateTimeField(default=datetime.datetime.now)),
                ('game_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbench.slip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
